changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: New Features
      labels:
        - enhancement
    - title: Bugfixes
      labels:
        - bug