name: Deploy Documentation (next)
on:
  push:
    branches: [next]
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm run docs
    - name: Upload
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        local-dir: ./docs/
        server-dir: ./next/doc/
        dangerous-clean-slate: true
