name: Deploy Storybook (next)
on:
  push:
    branches: [next]
jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm run build-storybook
    - name: Upload
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
        local-dir: ./storybook-static/
        server-dir: ./next/demos/
        dangerous-clean-slate: true